---
language: java

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

branches:
  only:
    - master
    - /^travis.*/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request
  - name: deploy docs
    if: (branch = master OR branch =~ ^.*-doc$) AND type != pull_request

jobs:
  include:
    - stage: test
      install: ./gradlew jvmTestClasses
      script: ./gradlew jvmTest jsTest
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: script
          script: ./gradlew publish --stacktrace

    - stage: deploy docs
      script: skip
      install: skip
      before_script:
        - "DEPLOY_DOCS=$(./gradlew properties | grep '^version:' | sed 's/version: //g' | grep -v SNAPSHOT) || echo 'Snapshot detected, skipping doc deploy'"
      before_deploy:
        - ./gradlew dokkaHtml
        - git add -f dokka
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            condition: $DEPLOY_DOCS
